### PR TITLE
Improving the readme.md for the new version

### LINKED ISSUE #118: 09.07.02 Readme
The release notes for NL-NL 09.07.02 language pack

### PR DESCRIPTION
**Pull request by EPTamminga**
Update for DNN 09.07.02
Close #118

### CODE REVIEW

**Review by mitchelsellers — APPROVED** [review]

**Review by mitchelsellers — CHANGES_REQUESTED** [review]
Sorry, this one apperas to revert version #'s down to 9.7.0, which I don't believe is desired.

**Comment by EPTamminga** [comment]
@mitchelsellers 
The version #'s in the files are changed by the release packaging process of @valadas . 
I must not change them myself.

**Comment by valadas** [comment]
Yeah, if you do it is not a big deal either, but yeah the release branch rewrites them

**Review by valadas — APPROVED** [review]
Looks good to me

**Review by mitchelsellers — APPROVED** [review]

**Pull request merged**
