### PR TITLE
Update GlobalResources.nl-NL.resx

### PR DESCRIPTION
**Pull request by aspelt**
Correctie in html weergave van sommige e-mailvelden.

### CODE REVIEW

**Review by valadas — CHANGES_REQUESTED** [review]
I believe this would need to be in an XML CDATA or such or it would be seen as XML and not HTML...

**Comment by valadas** [comment]
Some explanations here https://stackoverflow.com/questions/2784183/what-does-cdata-in-xml-mean

**Comment by aspelt** [comment]
@valadas: The issue was that the corrected fields dit generate incorrect mails with only HTML code. So I have copied the original text and did the translation. So I followed the original file in this case to correct the problem.

**Comment by aspelt** [comment]
Sorry! I will recheck the file.

**Pull request closed without merging**
