### PR TITLE
Update .NET license to standard text

### LINKED ISSUE #95: Update license with the standard .NET Foundation text
The text has to be:

```
Licensed to the .NET Foundation under one or more agreements.
The .NET Foundation licenses this file to you under the MIT license.
See the LICENSE file in the project root for more information
```

### PR DESCRIPTION
**Pull request by EPTamminga**
Close #95

### CODE REVIEW

**Comment by EPTamminga** [comment]
@david-poindexter The license text is NOT in source code, the text is in a .txt file, mentioned in the .dnn LP manifest. The license text is displayed during the extension install (the normal DNN extension license text).
I must not use 3 lines with // and without <br />, since the license display during (DNN extension) installation would not be readable as 3 lines.

**Comment by david-poindexter** [comment]
@EPTamminga I understand - sorry for any confusion.  My point was not the slashes (//), it was the actual text to be consistent with what is used in Dnn.Platform.  So, it would be something like the following if you wanted to use the `<br />` for HTML styling during the installation process:

```
<br />
Copyright (c) .NET Foundation. All rights reserved.<br />
Licensed under the MIT License. See LICENSE file in the project root for full license information<br /> 
```

**Comment by bdukes** [comment]
@david-poindexter, see https://github.com/dnnsoftware/Dnn.Platform/pull/3795#pullrequestreview-420105436, https://github.com/dotnet-foundation/foundation/blob/master/guidance/copyright.md, and https://github.com/dnnsoftware/Dnn.Platform/pull/3801.  This _is_ the new license header to be consistent with, based on @mitchelsellers' comments yesterday

**Comment by EPTamminga** [comment]
@bdukes @david-poindexter So my PR is correct?
If so, please review and process.

**Comment by bdukes** [comment]
In this case, I would think we would want the full license to be included in the package, rather then the "file header" version.  @valadas what do you think about copying the `LICENSE` file in the root into the zip during packaging?  Then we don't need to copies of the license file that can get out-of-sync?  In either case, the root `LICENSE` file needs to also be updated based on https://github.com/dotnet-foundation/foundation/blob/master/guidance/copyright.md#copyright, i.e. the start should be:

```
The MIT License (MIT)

Copyright (c) .NET Foundation and Contributors
All Rights Reserved

Permission is hereby granted... 
```

**Comment by EPTamminga** [comment]
@bdukes I think is it easier to do an URL in my license text that points to that formal license file on GitHub.

**Comment by bdukes** [comment]
👍 I think that's a great approach

**Comment by EPTamminga** [comment]
@bdukes Consider it done...
The URL link in the license.txt in the dnn manifest points to the license in the DNNPlatform repo. The license text is also updated in the LP repo

**Pull request merged**
